### ISSUE TITLE
Cannot destructure property 'series' of 'e' as it is undefined

### ISSUE THREAD

**Issue by leerob** [marbiano/marbiano.dev#3]
FYI from https://news.ycombinator.com/item?id=29590609

Might be due to DatoCMS + SSR?

**Comment by martinbavio** [comment]
@leerob absolutely missed this issue, thanks for taking the time to report it! It was indeed due to exceeding their monthly quota, forgot about adding some `Cache-Control` headers. 😅

**Comment by leerob** [comment]
No worries 😄 Glad you got it resolved!
